FROM python:3.11-slim

WORKDIR /app

COPY models/ ./models/
COPY backend/ ./backend/
COPY dist/ ./dist/

RUN pip install flask flask-cors numpy pandas scikit-learn xgboost joblib

EXPOSE 5000

CMD ["python3", "backend/server.py"]