import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { TrendingUp, TrendingDown, Minus, DollarSign, Calendar, MapPin, Store, Tag, Activity } from 'lucide-react';
import type { PredictionResponse } from '@/types';

interface PredictionResultProps {
  result: PredictionResponse | null;
}

export function PredictionResult({ result }: PredictionResultProps) {
  if (!result) return null;

  const { prediction, model_used, input_summary, contributions } = result;
  const modelLabel = model_used === 'xgboost' ? 'XGBoost (Tuned)' : model_used === 'random_forest' ? 'Random Forest' : 'Linear Regression';

  // Determine trend indicators
  const promoImpact = contributions?.Promo || 0;
  const holidayImpact = contributions?.Holiday || 0;
  const compImpact = contributions?.Competition || 0;

  return (
    <Card className="w-full shadow-lg border-slate-200">
      <CardHeader className="bg-gradient-to-r from-emerald-600 to-green-600 text-white rounded-t-lg">
        <CardTitle className="text-xl font-semibold flex items-center gap-2">
          <DollarSign className="w-5 h-5" />
          Prediction Result
        </CardTitle>
        <p className="text-emerald-100 text-sm">Sales forecast generated by {modelLabel}</p>
      </CardHeader>
      <CardContent className="pt-6 space-y-6">
        {/* Main Prediction */}
        <div className="text-center p-6 bg-gradient-to-b from-emerald-50 to-white rounded-xl border border-emerald-100">
          <p className="text-sm text-slate-500 mb-1">Predicted Daily Sales</p>
          <p className="text-5xl font-bold text-emerald-700">
            ${prediction?.toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}
          </p>
          <Badge className="mt-3 bg-emerald-100 text-emerald-800 hover:bg-emerald-200">
            {modelLabel}
          </Badge>
        </div>

        {/* Input Summary */}
        <div className="space-y-3">
          <h4 className="text-sm font-semibold text-slate-700 flex items-center gap-2">
            <Store className="w-4 h-4 text-slate-500" />
            Input Configuration
          </h4>
          <div className="grid grid-cols-2 gap-3 text-sm">
            <div className="flex items-center gap-2 p-2 bg-slate-50 rounded">
              <MapPin className="w-4 h-4 text-slate-400" />
              <span className="text-slate-600">Store Type:</span>
              <span className="font-medium capitalize">{input_summary?.store_type}</span>
            </div>
            <div className="flex items-center gap-2 p-2 bg-slate-50 rounded">
              <Tag className="w-4 h-4 text-slate-400" />
              <span className="text-slate-600">Assortment:</span>
              <span className="font-medium capitalize">{input_summary?.assortment}</span>
            </div>
            <div className="flex items-center gap-2 p-2 bg-slate-50 rounded">
              <Calendar className="w-4 h-4 text-slate-400" />
              <span className="text-slate-600">Date:</span>
              <span className="font-medium">{input_summary?.date}</span>
            </div>
            <div className="flex items-center gap-2 p-2 bg-slate-50 rounded">
              <Activity className="w-4 h-4 text-slate-400" />
              <span className="text-slate-600">Competition:</span>
              <span className="font-medium">{input_summary?.competition_distance}m</span>
            </div>
            <div className="flex items-center gap-2 p-2 bg-slate-50 rounded">
              <TrendingUp className="w-4 h-4 text-emerald-500" />
              <span className="text-slate-600">Promo:</span>
              <span className="font-medium">{input_summary?.promo ? 'Active' : 'Inactive'}</span>
            </div>
            <div className="flex items-center gap-2 p-2 bg-slate-50 rounded">
              <TrendingDown className="w-4 h-4 text-red-400" />
              <span className="text-slate-600">Holiday:</span>
              <span className="font-medium">{input_summary?.is_holiday ? 'Yes' : 'No'}</span>
            </div>
          </div>
        </div>

        <Separator />

        {/* Impact Factors */}
        <div className="space-y-3">
          <h4 className="text-sm font-semibold text-slate-700 flex items-center gap-2">
            <Activity className="w-4 h-4 text-slate-500" />
            Key Impact Factors
          </h4>
          <div className="space-y-3">
            <ImpactBar label="Promotion" value={promoImpact} icon={<TrendingUp className="w-4 h-4" />} />
            <ImpactBar label="Store Type" value={contributions?.['Store Type'] || 0.15} icon={<Store className="w-4 h-4" />} />
            <ImpactBar label="Day of Week" value={contributions?.['Day of Week'] || 0.1} icon={<Calendar className="w-4 h-4" />} />
            <ImpactBar label="Assortment" value={contributions?.['Assortment'] || 0.1} icon={<Tag className="w-4 h-4" />} />
            <ImpactBar label="Holiday Effect" value={holidayImpact} icon={<TrendingDown className="w-4 h-4" />} negative />
            <ImpactBar label="Competition" value={compImpact} icon={<Minus className="w-4 h-4" />} negative />
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

function ImpactBar({ label, value, icon, negative = false }: { label: string; value: number; icon: React.ReactNode; negative?: boolean }) {
  const absValue = Math.abs(value);
  const percentage = Math.min(absValue * 400, 100);
  const barColor = negative ? 'bg-red-500' : value >= 0 ? 'bg-emerald-500' : 'bg-red-500';

  return (
    <div className="space-y-1">
      <div className="flex justify-between items-center text-sm">
        <span className="flex items-center gap-1.5 text-slate-600">
          {icon}
          {label}
        </span>
        <span className={`font-medium ${negative ? 'text-red-600' : 'text-emerald-600'}`}>
          {value > 0 ? '+' : ''}{(value * 100).toFixed(0)}%
        </span>
      </div>
      <div className="w-full bg-slate-100 rounded-full h-2 overflow-hidden">
        <div
          className={`h-full rounded-full transition-all duration-500 ${barColor}`}
          style={{ width: `${percentage}%` }}
        />
      </div>
    </div>
  );
}
